import type { Metadata } from "next";
import "./globals.css";
import Topbar from "@/components/Topbar";
import Header from "@/sections/Header";
import Footer from "@/sections/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className="antialiased"
            >
                <Topbar />
                <div className="container-custom mx-auto">
                    <Header />
                    {children}
                </div>
                <Footer />
            </body>
        </html>
    );
}
